<?php 
return [
  'site' => [
    'ORDER_RETURN_TIME' => '86400*30',
    'ORDER_CONFIRM_PAY' => '86400*30',
    'ORDER_OVER_PAY' => '86400*30',
    'EMAIL_SENDER_NAME' => '荣先义',
    'EMAIL_SENDER_ADDRESS' => 'ahrongxianyi@163.com',
    'EMAIL_PASSWORD' => 'QTHUCYWWMIATQBQI',
    'EMAIL_USERNAME' => 'ahrongxianyi@163.com',
    'EMAIL_SMTP_AUTH' => '1',
    'EMAIL_PORT' => '994',
    'EMAIL_SMTP_SECURE' => 'ssl',
    'EMAIL_HOST' => 'smtp.163.com',
    'EMAIL_DEBUG_OUTPUT' => 'html',
    'EMAIL_SMTP_DEBUG' => '0',
    'SMS_APP_ID' => '9e72c6afaa5748d09cf2035258f613ed',
    'SMS_TOKEN' => '25798be441257d1ea1a6b105664c3840',
    'SMS_ACCOUNT_SID' => 'a1979e260cf49cbec7ad31f99734ed93',
    'WEB_STORE_DIR' => 'store',
    'WEB_STYLE' => 'default',
    'UPLOAD_TYPE' => 'jpg,png,gif,jpeg',
    'UPLOAD_PATH' => 'http://frontend.host.cms.com/uploads/',
    'CODE_FONT_SIZE' => '30',
    'HOME_SHOW_VERIFY' => '0',
    'SHOW_VERIFY' => '0',
    'CODE_LEN' => '4',
    'CODE_NOISE' => '0',
    'CODE_CURVE' => '0',
    'WEB_MAIN_DOMAIN' => 'mall',
    'REG_POINT' => '10',
    'WEB_IP_STATE' => '0',
    'REG_ON' => '1',
    'WEB_DESCRIPTION' => '测试',
    'WEB_KEYWORDS' => '测试',
    'VERSION' => 'Beta 1.0',
    'WEB_AUDIT_CODE' => '<script> var _hmt = _hmt || []; (function() {   var hm = document.createElement("script");   hm.src = "https://hm.baidu.com/hm.js?1083a5878eb7dd6e96e31da0b542e4a5";   var s = document.getElementsByTagName("script")[0];    s.parentNode.insertBefore(hm, s); })(); </script>',
    'WEB_ON' => '1',
    'COPY' => '阿西里西 ©版权所有 Axlix.com 2016-2020',
    'ICP' => '浙ICP备16022792号',
    'RECORD' => '技术支持联系方式:chaoren131415@126.com; QQ:953369865',
    'DOMAIN_NAME' => 'http://mall.axlix.com/',
    'WEB_COMPANY' => '测试',
    'WEB_TITLE' => '测试1111',
    'MYSQL_HOST' => '127.0.0.1',
    'MYSQL_PORT' => '3306',
    'DATA_TABLE_NAME' => 'yii2advanced',
    'BACKUP_PATH_NAME' => 'db',
    'BACKUP_PATH' => './backup/',
    'PART_SIZE' => '20971520',
    'COMPRESS' => '1',
    'COMPRESS_LEVEL' => '9',
  ],
];