<?php

namespace api\modules\v1\controllers;

use api\base\controllers\Auth;
use common\models\Store;
use common\models\StoreClass;
use jinxing\admin\helpers\Helper;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\Request;
use Yii;

/**
 * 店铺宝贝分类控制器
 * Class SellerStoreController
 */
class SellerStoreController extends Auth
{
    /**
     * 指定ORM模型
     * @var string
     */
    public $modelClass = 'common\models\StoreClass';

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

    /**
     * @var null 店铺ID
     */
    public $store_id = null;

    public function beforeAction($action)
    {
        $this->allowedApis = [];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 设置SEO
     * @return array
     */
    public function actionSeo()
    {
        return $this->success([
            'seo_title'     => Yii::$app->params['site']['WEB_TITLE'],
            'seo_keywords'  => Yii::$app->params['site']['WEB_KEYWORDS'],
            'seo_desc'      => Yii::$app->params['site']['WEB_DESCRIPTION'],
        ]);
    }

    public function actionIndex()
    {
        return new ActiveDataProvider([
            'query'         => StoreClass::find(),
            'pagination'    => new Pagination(['pageSize' => 50])
        ]);
    }

    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model   = new $this->modelClass;
        $model->attributes = $this->_getPost($request);
        if ($model->save()) {
            return $this->success();
        }
        return $this->error(Helper::arrayToString($model->getErrors()));
    }

    public function actionUpdate()
    {
        $request = Yii::$app->request;
        $model   = StoreClass::findOne(['id' => $request->post('id', 0)]);
        $model->attributes = $this->_getPost($request);
        if ($model->save()) {
            return $this->success();
        }
        return $this->error(Helper::arrayToString($model->getErrors()));
    }

    public function actionDelete()
    {
        $request    = Yii::$app->request;
        $ids        = $request->post('ids', '');
        $store_id   = $request->post('store_id', '');

        if (strpos($ids, ',') !== false) {
            $ids = implode(',', $ids);
        } else {
            $ids = array((int)$ids);
        }

        foreach ($ids as $item) {
            $store_class_one = StoreClass::findOne(['id' => $item, 'store_id' => $store_id]);
            if (is_null($store_class_one)) return $this->error('店铺分类名称id不存在');

            $child_class_all = StoreClass::findOne(['pid' => $item]);
            if (!is_null($child_class_all)) return $this->error('有子级分类不能删除');
        }

        StoreClass::deleteAll(['id' => $ids, 'store_id' => $store_id]);

        return $this->success();
    }

    /**
     * 异步检查分类名称是否重复
     */
    public function actionCheckClassName()
    {
        $store_name = Yii::$app->request->post('name', '');
        $class_id   = Yii::$app->request->post('class_id', 0);
        $class_pid  = Yii::$app->request->post('class_pid', 0);
        $store_id   = Yii::$app->request->post('store_id', 0);

        $where   = ['and'];
        $where[] = ['like', 'name', $store_name];
        $where[] = ['store_id' => $store_id];
        $where[] = ['class_pid' => $class_pid];
        if ($class_id) {
            $where[] = ['!=', 'id', $class_id];
        }

        if (!is_null($model = StoreClass::findOne($where))) {
            return $this->error('分类名称已经重复，请一个试试');
        }

        return $this->success([], 0, '验证通过');
    }

    /**
     * 获取店铺ID
     * @return array
     */
    private function _getStoreID()
    {
        return Store::find()->select('id')->where(['user_id' => Yii::$app->user->id])->column()[0];
    }

    private function _getPost(Request $request)
    {
        return [
            'name' => $request->post('name', ''),
            'title' => $request->post('title', ''),
            'keywords' => $request->post('keywords', ''),
            'desc' => $request->post('desc', ''),
            'is_nav' => $request->post('is_nav', 1),
            'status' => $request->post('status', 1),
            'sort' => $request->post('sort', 1),
            'pid' => $request->post('pid', 0),
            'store_id' => $this->_getStoreID(),
            'create_user_id' => Yii::$app->user->id,
        ];
    }
}
