<?php
namespace api\modules\v1\controllers;

use api\base\controllers\Auth;
use common\models\Store;
use Yii;

/**
 * 用户控制器
 * Class SellerController
 */
class SellerController extends Auth
{
    /**
     * 指定ORM模型
     * @var string
     */
    public $modelClass = '';

    public function beforeAction($action)
    {
        $this->allowedApis = [];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 设置SEO
     * @return array
     */
    public function actionSeo()
    {
        return $this->success([
            'seo_title'     => Yii::$app->params['site']['WEB_TITLE'],
            'seo_keywords'  => Yii::$app->params['site']['WEB_KEYWORDS'],
            'seo_desc'      => Yii::$app->params['site']['WEB_DESCRIPTION'],
        ]);
    }

    /**
     * 异步检查商家店铺名称是否重复
     */
    public function actionCheckStoreName()
    {
        $store_name = Yii::$app->request->post('name', '');
        $class_id   = Yii::$app->request->post('class_id', 0);
        $class_pid  = Yii::$app->request->post('class_pid', 0);
        $store_id   = Yii::$app->request->post('store_id', 0);

        $where      = ['and'];
        $where[]    = ['like', 'name', $store_name];

        if ($store_id) {
            $where[] = ['!=', 'id', $store_id];
        }

        if (!is_null($model = Store::findOne($where))) {
            return $this->error('店铺名称已经重复，请一个试试');
        }

        return $this->success([], 0, '验证通过');
    }
}
